name: Prevent Unauthorized PRs

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  check-author:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR Author
      id: check_author
      run: |
        AUTHOR=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
        MEMBERS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/microsoft/members | jq -r '.[].login')
        if echo "$MEMBERS" | grep -q "$AUTHOR"; then
          echo "Author is a Microsoft member."
        else
          echo "Author is not a Microsoft member."
          exit 1
        fi

  close-pr:
    needs: check-author
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Close PR
      run: |
        PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
        curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state": "closed"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}"
